### ISSUE TITLE
The formatter is removing indentation within `\:root`

### ISSUE THREAD

**Issue by codysherman** [TheRealSyler/sass-formatter#1]
**Describe the bug**
The formatter is removing indentation within `\:root`

**To Reproduce**
```
\:root
  --primary-color: red
```

**Expected behavior**
It should keep the indention of rules for the :root selector

**Desktop (please complete the following information):**
 - OS: Chrome OS 78
 - Version: 1.6.9

**Additional context**
`:root`
https://developer.mozilla.org/en-US/docs/Web/CSS/:root

In theory `:root` should be valid in [libsass from 3.5.0](https://sass-lang.com/documentation/style-rules/declarations#custom-properties) and on (and the backslash wouldn't be needed), but I have yet to avoid Sass complaining about it without the backslash without using Dart Sass. Thus the backslash is needed, and this is then broken when the formatter runs.

**Comment by TheRealSyler** [comment]
fixed
