### ISSUE TITLE
sass

### ISSUE THREAD

**Issue by amsuppi** [TheRealSyler/sass-formatter#14]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Version (of the extension) [e.g. 1.6]

**Additional context**

**Comment by TheRealSyler** [comment]
@amsuppi please don't open empty bug reports, feel free to reopen the issue if you edited the comment,  im closing this for now.
