### ISSUE TITLE
Autoindent on mixins with @content

### ISSUE THREAD

**Issue by LasseKrarup** [TheRealSyler/sass-formatter#18]
**Description**
When formatting a mixin which uses `@content`, the indentation of the mixin's content is incorrectly adjusted

**To Reproduce**
Format code with a mixin that uses `@content`

**Expected behavior**
Content of mixin should stay indented

**Actual behavior**
Mixin and content align to the same level of indentation

**Screenshots**
![Peek 2020-04-01 15-49](https://user-images.githubusercontent.com/32633899/78145406-23bc8b80-7431-11ea-94da-e2d51bd7d6d4.gif)

```sass
=desktop
    @media screen and (min-width: map-get($breakpoints, "desktop"))
        @content

.hero
    +desktop
        display: flex
        align-items: center

    *
        margin-left: auto
        margin-right: auto
```

**Desktop:**
 - OS: Linux Manjaro Kyria 19.0.2 
 - Version (of the extension): VS Code 1.8.1

**Comment by TheRealSyler** [comment]
@LasseKrarup its not a bug (#16), i really should add an option or rethink my approach because this seems to be a recurring issue.

**Comment by LasseKrarup** [comment]
I see how this can be interpreted as expected behavior, but I would like to add a feature request to possibly indent the `+mixin` syntax if there is nothing included in the parentheses of the mixin.
I see many people using the + syntax as an easy way of using eg. `@media` queries, so it might be a feature request to add:
```
element
    +mixin
        selector: attribute
```
as indented behavior, and keep mixins like these unindented:
```
element
    +mixin(45deg);
    &.another-selector: attribute
```

**Comment by webspilka** [comment]
One of the most popular packages uses this syntax https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass. As a result, all sites that use Bulma framework will no longer be able to use the sass-formatter ((.
This problem has already occurred and you fixed it https://github.com/TheRealSyler/vscode-sass-indented/issues/20, I will be grateful for the fix again.

**Comment by webspilka** [comment]
One of the most popular packages uses this syntax https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass. As a result, all sites that use Bulma framework will no longer be able to use the sass-formatter ((.
This problem has already occurred and you fixed it https://github.com/TheRealSyler/vscode-sass-indented/issues/20, I will be grateful for the fix again.
