### ISSUE TITLE
@extend bug

### ISSUE THREAD

**Issue by omersname** [TheRealSyler/sass-formatter#19]
if using @extend in the middle of a class it auto nesting everything below it in that class.
 
The problem:
![image](https://user-images.githubusercontent.com/37253325/79574357-b2cfd180-80c8-11ea-98b9-e3754afd5ae2.png)

It needs to be:
![image](https://user-images.githubusercontent.com/37253325/79574426-c844fb80-80c8-11ea-9fcb-45d3a17c8c53.png)

**Comment by omersname** [comment]
@TheRealSyler i did not understand the solution ?

**Comment by TheRealSyler** [comment]
@omersname a simple way to explain the solution is, the formatter thought that @extend is a block header (block headers are things like a class, id, mixin etc), now the formatter thinks that @extend is a property.

**Comment by omersname** [comment]
@TheRealSyler 
Did you fixed this bug?
Just update the extension?

**Comment by TheRealSyler** [comment]
@omersname yes, did fix the bug and no i did not update the extension, i won't update the extension or the formatter for a tiny bug fix like this.

**Comment by omersname** [comment]
Ok, I will try to find a major one....

**Comment by etothepi16** [comment]
I am also having this issue. Currently working around it by moving the @extend rule to the end of the block but it would be nice to have a proper fix. Please consider patching this!

**Comment by TheRealSyler** [comment]
@etothepi16 i guess have to do it, should be up within the next few minutes.
