### ISSUE TITLE
The formatter indent my sass code after +mixin

### ISSUE THREAD

**Issue by syyui15926** [TheRealSyler/sass-formatter#2]
**Describe the bug**
The formatter indent my sass code after +mixin cause compile error
**To Reproduce**
1. open sass file
2. right click on text editor
3. click format document

**Expected behavior**
I expected the formatter avoid +mixin

**Screenshots**
after format:
![2019-11-17](https://user-images.githubusercontent.com/40348033/69002518-d630fd80-092b-11ea-90e0-c90c4ba13256.png)
original code:
https://paste.ofcode.org/jajW994tRXaSYPZzdfZ9u

**Desktop (please complete the following information):**
windows 10 home
version 1809
**Additional context**

**Comment by TheRealSyler** [comment]
@syyui15926 please open formatter related issues in this repo, i think i know why that is happening ill fix it, soon ish, until i fixed that you can do something like this: 
```sass
   .line1,.line2
      +size(150px,10px)
      //R
      background-color: white
      position: absolute
      //R
      +center
      transition-duration: 1s
````
The `//R` flag resets the indentation, its meant to fix stuff like this while im working on a solution.

**Comment by TheRealSyler** [comment]
i looked into this, so the conclusion is this is expected behavior, the reason is the mixin get treated as a selector and since there is no way(without adding a lot of extra code) to check weather `+anything` is a selector or mixin the formatter treats it as a selector, use `@include` instead of + or disable the formatter.

**Comment by TheRealSyler** [comment]
`+mixin` gets treated as include mixin `+ mixin` gets treated as a selector.
