### ISSUE TITLE
Block comment indented on first line (*.sass syntax)

### ISSUE THREAD

**Issue by andi1984** [TheRealSyler/sass-formatter#21]
**Describe the bug**
First line of a block comment is indented.

**To Reproduce**

```css
.a
  color: red

 /*
 * My block comment
 */
.something-else
  color: red
```

Format this code with the formatter and it will return the first line of the block comment (the "/*") will be indented.

**Expected behavior**
Not indenting the first line of the block-comment

**Desktop (please complete the following information):**
 - OS: Mac
 - Version (of the extension) [e.g. 1.6]: 1.8.3

**Comment by TheRealSyler** [comment]
i can reproduce the issue, thanks for reporting.
