### ISSUE TITLE
Format on save reindents lines

### ISSUE THREAD

**Issue by lars-timezynk** [TheRealSyler/sass-formatter#22]
**Describe the bug**
When saving, some lines lose an indentation.

**To Reproduce**
This seems to affect indentation at the end of a definition:

	svg.canvas
		width: 100vw
		height: 100vh

		path
			stroke: $outline
			fill: transparent
			stroke-width: 2

This snippet, when pressing ctrl + s, is changed to:

	svg.canvas
		width: 100vw
		height: 100vh

		path
		stroke: $outline
		fill: transparent
		stroke-width: 2

 - OS: Ubuntu 20.04
 - Version: 1.8.3

**Comment by TheRealSyler** [comment]
thanks for opening the issue, i fixed the bug, not sure when i will update the extension.
