### ISSUE TITLE
nth-child property (background color) loses indent

### ISSUE THREAD

**Issue by dax-westerman** [TheRealSyler/sass-formatter#25]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

**Describe the bug**
When SASS reference to alternating table row exists, background color loses indent

```
tr:nth-child(2n+1)
    background-color: $alt-row-color
```
formats to
```
tr:nth-child(2n+1)
background-color: $alt-row-color
```

**To Reproduce**
Create SASS file in VS Code with 

```
tr:nth-child(2n+1)
    background-color: $alt-row-color
```

then format.

**Expected behavior**
Keeps original formatting

**Screenshots**

![image](https://user-images.githubusercontent.com/11837526/84779121-9efdfa00-afa9-11ea-972a-d0ee15de7052.png)

![image](https://user-images.githubusercontent.com/11837526/84779101-97d6ec00-afa9-11ea-867e-e9e799403555.png)

**Comment by TheRealSyler** [comment]
@dax-westerman i fixed the issue.
