### ISSUE TITLE
Wrong indents for `top'

### ISSUE THREAD

**Issue by kissge** [TheRealSyler/sass-formatter#26]
**Describe the bug**
The formatter formats the following snippet improperly, i.e.

```sass
@keyframes foo
  from
    top: 0px
```

is formatted as:

```sass
@keyframes foo
  from
  top: 0px
```

Looks like only the word `top' is affected. See the screenshot below.
My guess is this regexp needs improvement.
https://github.com/TheRealSyler/sass-formatter/blob/8ba7bf9504843f0ab1aadb6a8f6daa801bc0322d/src/utility.ts#L53

**To Reproduce**
Format the code above.

**Expected behavior**
The indent is already correct and nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/4177010/85912735-d1410e80-b869-11ea-856c-5682740f3c3e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version (of the extension) syler.sass-indented 1.8.6

**Additional context**
n/a

**Comment by TheRealSyler** [comment]
@kissge thanks for making me aware,  the regex didn't have `$` at the end so it makes sense that `top` was recognized as a keyframe point.
