### ISSUE TITLE
feat(docs): add chainWebpack/extendWebpack docs

### ISSUE THREAD

**Issue by mesqueeb** [TheRealSyler/sass-formatter#28]
I'd love some documentation on how to add this via chainWebpack/extendWebpack.

**Comment by TheRealSyler** [comment]
@mesqueeb  i have no idea what you mean by `add this via chainWebpack/extendWebpack`, the formatter is supposed to be used before you bundle it with webpack or any other bundler.

**Comment by mesqueeb** [comment]
@TheRealSyler thanks for your comment.
I'm not 100% sure actually, I was envisioning something like how you can add ESLint to Webpack settings.

I'm just wondering how I can enforce that sass-formatter runs for people on the team that don't use VSCode or don't have the correct extension installed.
Any hints?

**Comment by TheRealSyler** [comment]
i think i know what you want to do, if i'm correct then you would need to create a simple cli/simple script that runs the sass-formatter before you commit to github, or at any other point.

a simple example, create a `formatSass.ts` script like this one
```ts
import { SassFormatter } from 'sass-formatter';

function async formatProject() {
  const sassFiles = // load all sass file paths in the project.
  for (let i = 0; i < sassFiles.length; i++){
    const path = sassFiles[i];
    const file = await readFile(path) // replace with actual read file func.

    const result = SassFormatter.Format(file);
    await writeFile(path, result); // replace with actual write file func
  }
}
(async () =>formatProject())()
```

and then run it when you need it with `ts-node formatSass.ts`

**Comment by TheRealSyler** [comment]
im closing this issue, if you feel like its not resolved you can reopen the issue.
