### ISSUE TITLE
variables are not decremented

### ISSUE THREAD

**Issue by mesqueeb** [TheRealSyler/sass-formatter#29]
**Describe the bug**

variables are not decremented

**To Reproduce**

add
```
$var1 = black
 $var2 = blue
```

**Expected behavior**

should auto format to:

```
$var1 = black
$var2 = blue
```

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Version (of the extension) [e.g. 1.6]

VSCode add-on last version

**Comment by TheRealSyler** [comment]
i think this is expected behavior, because variables don't get formatted but im not sure, ill look into this.

i might change this so that variables get treated the same as any other property.
