### ISSUE TITLE
Formatting multiple lines of comment errors-格式化多行注释出错

### ISSUE THREAD

**Issue by Teemwu** [TheRealSyler/sass-formatter#3]
**Describe the bug**
格式化后，多行注释会被转换成 “ \*/ ”
google translate：After formatting, multi-line comments will be converted to "\*/"

**To Reproduce**

**Expected behavior**

**Screenshots**
格式化前
Before formatting
![image](https://user-images.githubusercontent.com/16522288/69221566-8dd74100-0bb2-11ea-97b8-cf7d9a6590bd.png)
格式化后
After formatting
![image](https://user-images.githubusercontent.com/16522288/69221605-a6dff200-0bb2-11ea-93e6-2cebc2b63c95.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Version (of the extension) [e.g. 1.6]

**Additional context**

**Comment by TheRealSyler** [comment]
fixed.
