### ISSUE TITLE
wrong indentation when using mixin

### ISSUE THREAD

**Issue by mesqueeb** [TheRealSyler/sass-formatter#32]
## input
```sass
=header-globals()
  font-family: 'Poppins', sans-serif

=t-h1()
  +header-globals
  font-weight: $bold
```
## expected output (same as above)
```sass
=header-globals()
  font-family: 'Poppins', sans-serif

=t-h1()
  +header-globals
  font-weight: $bold
```
## current behaviour
```sass
=header-globals()
  font-family: 'Poppins', sans-serif

=t-h1()
  +header-globals
    font-weight: $bold
```
last line gets an indentation that's unwanted

**Comment by mesqueeb** [comment]
@TheRealSyler is it possible to add issue hunt funding to this issue?

**Comment by TheRealSyler** [comment]
sure, but im not sure that this is a bug think i changed it a while ago but i don't remember why, "fixing" this is really easy i just have to move a regex from one if statement to another, i will fix or leave as it is later today, and get back to you.

**Comment by TheRealSyler** [comment]
okay read #18, if you use `+mixin()` you don't get indentation on the next line, i think i really need to add that you can do it both ways but for now im closing this issue.

**Comment by mesqueeb** [comment]
even if I add `()` or not at the end, it's the same behaviour for me:

![2020-09-04 10 13 48](https://user-images.githubusercontent.com/3253920/92188390-7219fe80-ee97-11ea-9439-5b3e04c94665.gif)

**Comment by TheRealSyler** [comment]
@mesqueeb try again.

**Comment by mesqueeb** [comment]
It's been fixed for me ever since you closed the issue !
I was forced to use () everywhere but that's ok for me.
