### ISSUE TITLE
Necessary indent removed when line ending is crlf.

### ISSUE THREAD

**Issue by crupest** [TheRealSyler/sass-formatter#35]
**Describe the bug**
Some necessary indent is removed when the file's line ending is `crlf`. When I change it to `lf`, it works right.
I' m not sure it is a bug of formatter or some conflict of extensions, maybe, or other things.

**To Reproduce**
Create a file with `.sass` extension in name. **Make sure line ending is `crlf`.** Add following code:
``` sass
@keyframes aaa
  from
    background: white
  to
    background: black
```
Then format, it turns to
```
@keyframes aaa
  from
  background: white
  to
  background: black
```

Undo format and change the file line ending to `lf`. Then format again. It remains the correct format.

**Expected behavior**
In `crlf`, it should be formatted to
``` sass
@keyframes aaa
  from
    background: white
  to
    background: black
```

**Screenshots**
No.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version (of the extension): `1.8.11`

**Additional context**
Some other extensions I used which might interfere:
- `prettier`
- `EditorConfig`

(Update: I tried to disable two extensions above, the bug remained.)

Preferences related are all default.

By the way, VS Code version is `1.49.2`.

**Comment by TheRealSyler** [comment]
@crupest i confirmed the bug, i think i just need to replace `\n` with `\r\n` in all my regex's so this should be an easy fix.

**Comment by crupest** [comment]
I'm not quite familiar with formatter internals. Your fix is reasonable. I think a good start would be to write some unit tests against this, which I could help do if I have time.

**Comment by TheRealSyler** [comment]
thanks but that not necessary, i added the info as a reminder for me so that i know what i have to do.

**Comment by crupest** [comment]
That would be nice then! Thank you for your devotion!😁

**Comment by TheRealSyler** [comment]
@crupest it works now in the formatter i just need to update the extension, im not sure if i can use the line endings from vscode or if you have to select the line ending manually in any case new version should be up in a less that a hour.

**Comment by crupest** [comment]
It would be better if formatter could keep the original line ending. So I think it is not necessary to use it from vscode as long as vscode passes the original line ending to extension. Whatever, giving the correct format is more important and line ending change is trivial, whose only concern is unnecessary change in git history.
