### ISSUE TITLE
Export `defaultSassFormatterConfig` or `getDefaultSassFormatterConfig`

### ISSUE THREAD

**Issue by octref** [TheRealSyler/sass-formatter#36]
Hi @TheRealSyler, thanks a lot for your work. I see recently you added CRLF support. When I upgraded, I needed to manually add the `lineEnding` confing to avoid compile error.

What do you think about exposing either an object `defaultSassFormatterConfig` of type `SassFormatterConfig`, or a function `getDefaultSassFormatterConfig` that returns `SassFormatterConfig`? Currently the defaults are in the comments and not accessible through API.

Thanks again for your amazing work 👍

**Comment by TheRealSyler** [comment]
@octref i added a defaultSassFormatterConfig object.

 you can probably just delete everything from [line 44](https://github.com/vuejs/vetur/blob/44afe24476a4d4c29a6f34786caf9c8a3b5189e7/server/src/modes/style/sass/sassLanguageMode.ts#L44) to [line 58](https://github.com/vuejs/vetur/blob/44afe24476a4d4c29a6f34786caf9c8a3b5189e7/server/src/modes/style/sass/sassLanguageMode.ts#L58) and replace it with

 ```ts
  if (this.config.vetur.format.defaultFormatter.sass === 'sass-formatter') {
      return [TextEdit.replace(range, SassFormatter.Format(document.getText(range),  {...formattingOptions, ...this.config.sass.format}))];
  }
````

the formatter will make sure that the options are valid i added that a while ago, now you don't need to pass all the options just the ones you want to change.

i can create a pr if you want to, let me know what you want to do.

**Comment by octref** [comment]
@TheRealSyler I could do that, but that presumes people having sass extension installed. So I still think having a default config would make sense.
