### ISSUE TITLE
wrong format of sass mixins on save

### ISSUE THREAD

**Issue by F-y-o-d-o-r** [TheRealSyler/sass-formatter#38]
**Describe the bug**
wrong sass mixins formating

**To Reproduce**
to format

**Expected behavior**
It should have an indent like this:
![image](https://user-images.githubusercontent.com/25505945/104453747-8ab8c480-55ad-11eb-8bdb-e601a27be5d9.png)

**Screenshots**
but it breaks all code:
![image](https://user-images.githubusercontent.com/25505945/104453820-acb24700-55ad-11eb-8432-4b7f41ab23e8.png)

My mixin:
![image](https://user-images.githubusercontent.com/25505945/104453925-d53a4100-55ad-11eb-911b-9c1a726f1f02.png)
```sass
=r($width)
  @media only screen and (max-width: $width+ "px")
    @content

.container-1475
  margin-left: auto
  margin-right: auto
  width: 100%
  max-width: 1475px
  +r(1800)
    padding-left: 20px
    padding-right: 20px
```

**Desktop (please complete the following information):**
 - OS: linux ubuntu, windows 10
 - Version (of the extension) [e.g. 1.6]

**Additional context**
Sass extension in vscode
![image](https://user-images.githubusercontent.com/25505945/104455026-61993380-55af-11eb-8126-7dbd1143486a.png)

**Comment by TheRealSyler** [comment]
its not a bug its expected behaviour, i will change it in the future but im not sure when, for more details read #32.

**Comment by F-y-o-d-o-r** [comment]
> its not a bug its expected behaviour, i will change it in the future but im not sure when, for more details read #32.

I read this but he has the opposite problem )
sometimes this space needs to be added and sometimes not, depending on the mixin ..
he doesn't need a space, but I need ...

**Comment by mesqueeb** [comment]
@TheRealSyler it sounds like since in Sass both syntaxes are correct depending on the situation, you should just remove any auto formatting of indentation underneath a mixin. What do you think ?

**Comment by TheRealSyler** [comment]
@mesqueeb yep, thats the plan.

**Comment by TheRealSyler** [comment]
@F-y-o-d-o-r should be fixed now.
