### ISSUE TITLE
Auto tab @import the end file

### ISSUE THREAD

**Issue by Merakaa** [TheRealSyler/sass-formatter#46]
**Describe the bug**
Auto tab in end sass file for @import.

**To Reproduce**
Add any class. The end import any file.

**Expected behavior**
No spaces.

**Screenshots**
I wanna:
 
![1](https://user-images.githubusercontent.com/31518980/105813135-306a2b80-5fd1-11eb-8a7b-49aada9149a2.jpg)

I have: 
![2](https://user-images.githubusercontent.com/31518980/105813140-33651c00-5fd1-11eb-9053-dec3ac398bc0.jpg)

```
.master
  display: none
  &.active
    display: block

@import "media"
```

**Desktop (please complete the following information):**
 - OS: win 8.1
 - Version (of the extension) 1.8.14

**Comment by TheRealSyler** [comment]
thanks for reporting, seems like the last update broke a few things.

**Comment by TheRealSyler** [comment]
@Merakaa should be fixed, i will update the extension within a day or two.
