### ISSUE TITLE
Broken output when selector is written in string literal + variable

### ISSUE THREAD

**Issue by kissge** [TheRealSyler/sass-formatter#61]
**Describe the bug**
The following SASS code is formatted improperly.

**Code**
```sass
// This is OK
@for $i from 1 through 6
  #{'h' + $i + '::before'}
    color: red

// This is broken by sass-formatter
@for $i from 1 through 6
  h#{$i}
    color: red

// Also this
@for $i from 1 through 6
  #{'h' + $i}::before
    color: red
```

**To Reproduce**
Paste it to https://sass-formatter.syler.de/
    
**Expected behavior**
No changes

**Actual output**
```sass
// This is OK
@for $i from 1 through 6
  #{'h' + $i + '::before'}
    color: red

// This is broken by sass-formatter
@for $i from 1 through 6
  h#{$i}
  color: red

// Also this
@for $i from 1 through 6
  #{'h' + $i}: :before
  color: red
```

**Comment by TheRealSyler** [comment]
Thanks for reporting ill take a look at at it, i think i already know whats the problem, should be fixed today, if not ill let you know.

**Comment by kissge** [comment]
Wow, quick!
Actually the first example should be a fair workaround, so just take your time 🙇🏽
