### ISSUE TITLE
Broken output when square bracket and `=` is used right after nested block

### ISSUE THREAD

**Issue by kissge** [TheRealSyler/sass-formatter#62]
**Describe the bug**
The following SASS code is formatted improperly (but apparently still valid).

**Code**
```sass
// This is OK
.a
  .b
    color: black

a[href]
  color: red

// This is broken
.a
  .b
    color: black

a[href="/"]
  color: green
```

**To Reproduce**
Paste it to https://sass-formatter.syler.de/
    
**Expected behavior**
No changes

**Actual output**
```sass
// This is OK
.a
  .b
    color: black

a[href]
  color: red

// This is broken
.a
  .b
    color: black

a[href="/"]
    color: green
```

**Comment by TheRealSyler** [comment]
@kissge so i fixed both issues, i will update the extension later today, thanks again for reporting the issues.
