### ISSUE TITLE
Incorrect formatting for unknown elements

### ISSUE THREAD

**Issue by OpportunityLiu** [TheRealSyler/sass-formatter#64]
**Describe the bug**
When formatting a nested unknown element, its properties' indent will be removed.

**To Reproduce**
Format this
```sass
:host
  contain: content
  slot
    display: grid
```
Will get this
```sass
:host
  contain: content
  slot
  display: grid
```

**Expected behavior**
Correct formatting of unknown elements

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version (of the extension) 1.8.21

**Additional context**
![image](https://user-images.githubusercontent.com/13471233/176663438-b5e0437c-682c-44c2-99c2-9953d21d145c.png)
![image](https://user-images.githubusercontent.com/13471233/176664011-3631d1b6-6168-4468-9aba-24ff8582d169.png)

Also, the syntax highlighting of newly added elements and pseudo-classes is incorrect.

**Comment by TheRealSyler** [comment]
fixed in 679bc56bc46ae04ad85b63b0b144f3a531f777f5
