### ISSUE TITLE
scss code format

### ISSUE THREAD

**Issue by samrajforit** [TheRealSyler/sass-formatter#65]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Version (of the extension) [e.g. 1.6]

**Additional context**

**Comment by samrajforit** [comment]
sass code formatting is not working, for example it doesn't format my scss code and not popping any suggestions. Can you please help? Thank you

**Comment by TheRealSyler** [comment]
this formatter is only for `.sass`, `.scss` is built in to vscode.
