### ISSUE TITLE
formatter didn't working

### ISSUE THREAD

**Issue by chobijaeyu** [TheRealSyler/sass-formatter#7]
**Describe the bug**
save file and nothing happend

**To Reproduce**
change some code and save

**Desktop (please complete the following information):**
 - OS: macos
 - Version (of the extension) 1.6.9 (syler.sass-indented installed )

**Additional context**
thanks for your time

**Comment by TheRealSyler** [comment]
* Try
  * calling the formatter from the command palette.
  * to look if the formatter is disabled in the settings.
  * updating the extension to the latest version (1.7.1)

**Comment by chobijaeyu** [comment]
@TheRealSyler thanks .

I manually `rm -rf ~/.vscode/extensions/syler.sass-indented-1.7.1`

 reinstall again,it's working.

(by push `option + shift +f`).

thanks for your amazing work
