### ISSUE TITLE
Bug, formatter applied inside Block Comments

### ISSUE THREAD

**Issue by rkmfl** [TheRealSyler/sass-formatter#73]
**Describe the bug**
Block Comments (multi-line comments) such as `/* */` often cause a problem for sass-formatter when they include certain characters.

**To Reproduce**
The following is a simple example. There are many more:
```html
/*
 Grid: x

 Clamp: y
*/
```

**Expected behavior**
Ignore everything between /* matching brackets */ without exception.

For example, in regex:
```regex
\/\*[\s\S]*?\*\/
```

**Application:**
VS Code (all versions tested including current 1.81.1)

**Comment by TheRealSyler** [comment]
@rkmfl fixed it, will be published soon ish.
