### ISSUE TITLE
Invalid pseudo class formating

### ISSUE THREAD

**Issue by Nanimo1309** [TheRealSyler/sass-formatter#74]
In sass file formats this:
```
div:first-child > div
    width: 100px
```
Into this:
```
div: first-child > div
width: 100px
```
Notice space after colon after div

 - OS: Linux Mint (#98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64)
 - Version (of the extension): 1.8.28

**Comment by Nanimo1309** [comment]
PS: For those who came here with this issue you can do:
```
div:first-child
    > div
        width: 100px
```

**Comment by TheRealSyler** [comment]
@Nanimo1309 thanks for letting me know, i will look into it.
