### ISSUE TITLE
Bug de indentação

### ISSUE THREAD

**Issue by RafaelMagnoC** [TheRealSyler/sass-formatter#75]
**Describe the bug**
Sempre que salvo meu arquivo ou utilizo atalho para formatar o documento, o valor da propriedade no arquivo sass vai pra frente.

**To Reproduce**
utilizando visual studio code, basta apertar o ctrl + s ou alt + shift + f em qualquer arquivo .sass

**Expected behavior**
meu arquivo deveria ser salvo sem alterar a indentação do meu arquivo .sass

**Screenshots**
![Untitled](https://github.com/TheRealSyler/sass-formatter/assets/75619754/66d60cf5-88d7-4df3-bb64-9c8487aacac4)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version: @#h2

**Additional context**
Não tem mais o que falar.

**Comment by TheRealSyler** [comment]
I was not able to reproduce the issue, i tried the following text on [sass-formatter.syler.de](https://sass-formatter.syler.de/) and it formatted correctly, im guessing that you have another extension installed, please reopen the issue if you can reproduce the issue on [sass-formatter.syler.de](https://sass-formatter.syler.de/) or in vscode with all (except sass) extensions disabled.

```sass
@use 'header'
@use 'grid.layout'
@use 'variants'

*
  margin: 0
  padding: 0
  box-sizing: border-box
  font-familiy: variants.$font-stack

#menu
  background-color: green

```

**Comment by RafaelMagnoC** [comment]
Leonardo, bom dia! Eu desinstalei todas possíveis extensões que pudessem
causar incompatibilidade e mesmo assim o problema persistiu.

Para otimizar o tempo, eu redefini todas configurações do visual studio
code para o modo padrão e deu certo!

Acredito que o problema foi causado por alguma configuração de extensão que
persistiu mesmo ao ser removida.

Obrigado pela atenção!

Em qua., 3 de abr. de 2024 às 06:33, Leonard Grosoli <
***@***.***> escreveu:
